name: Build A50-1 RMK Firmware

on:
  workflow_dispatch:

  push:
    paths:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: thumbv7em-none-eabihf

      - name: Install cargo-make
        uses: davidB/rust-cargo-make@v1

      - name: Build UF2
        run: cargo make uf2

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: A50-1-firmware
          path: |
            **/*.uf2
